### ISSUE TITLE
Missing descriptions for list - authorization_profile.create - advanced_attributes

### ISSUE THREAD

**Issue by eiddor** [CiscoISE/ciscoisesdk#10]
I've noticed that some parameters that are objects or lists do not have documentation on what those objects can/should contain.

For instance:

https://ciscoisesdk.readthedocs.io/en/latest/api/api.html?#ciscoisesdk.api.v3_0_0.authorization_profile.AuthorizationProfile.create_authorization_profile

The `advanced_attributes` parameter is a list that can contain a number of fields that are is documented in the ISE API:

https://developer.cisco.com/docs/identity-services-engine/v1/#!authorizationprofile

There are a few other examples of this that I'm finding and I will open an issue for the ones that I come across.

Thanks!

**Comment by wastorga** [comment]
@eiddor

The advanced_attributes parameter is now included in the documentation of the [AuthorizationProfile](https://ciscoisesdk.readthedocs.io/en/latest/api/api.html?#ciscoisesdk.api.v3_0_0.authorization_profile.AuthorizationProfile) module. It is the best that we can do right now.

**Comment by eiddor** [comment]
Thanks @wastorga!
