### ISSUE TITLE
Missing descriptions for objects - authorization_profile.create - webRedirection

### ISSUE THREAD

**Issue by eiddor** [CiscoISE/ciscoisesdk#11]
I've noticed that some parameters that are objects do not have documentation on what those objects can/should contain.

For instance:

https://ciscoisesdk.readthedocs.io/en/latest/api/api.html?#ciscoisesdk.api.v3_0_0.authorization_profile.AuthorizationProfile.create_authorization_profile

The `webRedirection` object can contain a few attributes that are documented in the ISE API:

https://developer.cisco.com/docs/identity-services-engine/v1/#!authorizationprofile

There are a few other examples of this that I'm finding and I will open an issue for the ones that I come across.

Thanks!

**Comment by wastorga** [comment]
Hi, @eiddor .
The input files that we use to create the SDK have those descriptions as HTML tables, making it difficult to obtain each parameter method's full description.

We converted the format to use that table description into the module documentation.
Please, take a look, https://ciscoisesdk.readthedocs.io/en/develop/api/api.html#authorization-profile-3-1-1.

There are still some issues with the conversion of unusual tables. Those tables seem to be limited to the Revision History. We are working on them.

**Comment by eiddor** [comment]
Thanks @wastorga - this definitely helps a bit more for those who are diving into some of this stuff for the first time.

(I didn't think that HTML tables were still around!)

**Comment by wastorga** [comment]
@eiddor 

Both parameters are now included in the documentation of the [AuthorizationProfile](https://ciscoisesdk.readthedocs.io/en/latest/api/api.html?#ciscoisesdk.api.v3_0_0.authorization_profile.AuthorizationProfile) module. It is the best that we can do right now.

**Comment by eiddor** [comment]
Thanks @wastorga!
