### ISSUE TITLE
get_endpoints_generator() fails to return last page

### ISSUE THREAD

**Issue by jeremypng** [CiscoISE/ciscoisesdk#15]
**Prerequisites**
* [yes ] Have you tested the operation in the API directly?
* [ yes] Do you have the latest SDK version?

**Describe the bug**
When using the get_endpoints_generator the last page produces an error on line 444 of utils.get_next_page()
Exception has occurred: TypeError    
can only concatenate list (not "int") to list
Starting line 437 of utils.py:
```python
        if not found:
            if isinstance(result, list):
                if len(result) == 0:
                    yield response
                else:
                    _params = dict(params)
                    if 'page' in params and 'size' in params:
                        _params['page'] = (params['page'] or 1) + 1
```

values from debugger output:
```
params['page']
['4']
(params['page'] or 1) + 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: can only concatenate list (not "int") to list
```

**Expected behavior**
The final results page should be yielded by the generator. The results variable in the get_next_page() function already has the results. The logic error in utils.get_next_page(). When the get_next_page() function does not find the nextPage attribue on line 424 it should return the current page. However, when it drops into the if block on line 437, it gets to line 444 and hits the TypeError. I'm not sure how that line could ever work because in my debugging, that value, params['page'], is always a list of strings with one entry. I can get it to work for my purposes by changing line 439 from:
```python
if len(result) == 0:
```
to:
```python
if len(result) >0:
```
But because I'm not sure what the rest of that function is trying to accomplish (lines 441 and following), I'm afraid that might not be the right way to fix this.

**Environment (please complete the following information):**
* ISE version and patch: 3.0.0.458 patch 4
* Python version:  3.8.2
* SDK version: 1.3.1
* OS version: Ubuntu 20.04.1

**Additional context**

**Comment by wastorga** [comment]
Hi, @jeremypng.
Sorry, I did not know that we had auto close on.

I tested many generator functions with different size parameters on ISE 3.1.1. However, if the problem persists, please feel free to comment.

Just as a reminder. As stated in the documentation, the minimum supported version is ISE 3.1. Future releases may drop the ISE version 3.0.0.

**Comment by jeremypng** [comment]
DNAC doesn't support ISE 3.1 yet.. Hard to get there.
