### ISSUE TITLE
Are there more examples available? 

### ISSUE THREAD

**Issue by OlegPekar** [CiscoISE/ciscoisesdk#18]
I need to add NetworkDevice with RADIUS protocol enabled and some settings around. How can I do that? Are there more examples that allow understanding of how to configure specific things?

**Comment by einarnn** [comment]
do you want to use Ansible or just the Python `ciscoisesdk`?

**Comment by bvargasre** [comment]
Hi @OlegPekar Is the information provided sufficient to clarify your doubts?
If so, feel free to close the issue. 
If there are no other questions, the issue will be closed within 48 hours.
