### ISSUE TITLE
InsecureRequestWarning on verify=false

### ISSUE THREAD

**Issue by oliverl-21** [CiscoISE/ciscoisesdk#2]
while using the sdk through the ansible module with the option verify=false the following message is shown:

![grafik](https://user-images.githubusercontent.com/77393143/123425044-e5753400-d5c1-11eb-9a06-d49f82a83327.png)

would be great to have an additional option or include it in verify=false to disable those warnings.
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

urllib3.disable_warnings()

**Comment by wastorga** [comment]
v1.0.1 with verify=false now disables those warnings
