### ISSUE TITLE
RestResponse Class: Add HTTP status code as property

### ISSUE THREAD

**Issue by netgab** [CiscoISE/ciscoisesdk#22]
**Is your feature request related to a problem? Please describe.**
For regression testing using pyATS (or other testing tools), it might be useful to get the HTTP status code in successful API requests (e.g. 201 when creating a resource like an endpoint). In case of an error (`ApiError` exception) the fail status code is already implemented in the `status_code` property.

**Describe the solution you'd like**
Add the following properties to the `RestResponse` class:
- `status_code`

The field `status` might not be needed, because I doubt the ISE will add any message in the body for success requests.

**Comment by wastorga** [comment]
The ciscoisesdk v1.5.0 is up. Feel free to test it and close or comment if necessary.

**Comment by netgab** [comment]
Works perfectly. Thanks!
