### ISSUE TITLE
Automatic loading of additial pages and merge results

### ISSUE THREAD

**Issue by netgab** [CiscoISE/ciscoisesdk#24]
**Is your feature request related to a problem? Please describe.**
If I query ISE ERS API object (for example `endpoint`), the resulting list is limited to 20 items by default as described in the [ISE API documentation](https://developer.cisco.com/docs/identity-services-engine/v1/#!read-a-resource). This can be increased to some value using the `size` parameter in the corresponding get call.
However, based on the ISE documentation, the "_maximum resources per page cannot be more than 100 resources_". So I assume the `size` parameter must not exceed 100 as well.

Example:
```python
  epQuery = self.iseApi.endpoint.get_endpoints(
      filter=f'groupId.EQ.greatDevices',
      size=100
  )
```
If more than 100 return items are in the list, the next result page must be loaded manually.
So a query where the number of items is not sure in the first place must be include some type of looping to get all results.
Example:
```python
        try:
            epQueryResult = None
            paging = True
            currentPage = 1
            while paging:
                epQuery = self.iseApi.endpoint.get_endpoints(
                    filter=f'groupId.EQ.greatDevices',
                    page=currentPage)
                
                # Extend result dictionary
                if epQueryResult:
                    # Case1: Result dictionary is already populated (page > 1)
                    epQueryResult["SearchResult"]["resources"].extend(
                        epQuery.response["SearchResult"]["resources"]
                    )
                else:
                    # Case2: Result dictionary is empty (page 1)
                    epQueryResult = epQuery.response

                # Checking if there is a nextPage reference
                if epQuery.response.SearchResult.nextPage:
                    currentPage += 1
                else:
                    paging = False

```

**Describe the solution you'd like**
Automatic paging for query results returning a list (`response["SearchResult"]["resources"]`).

**Describe alternatives you've considered**
See code example above

**Comment by wastorga** [comment]
Hi, @netgab.
A feature like this is already present in the SDK, with the generator functions. 
In this case get_endpoints_generator or get_all_generator (alias).
I provided one example,  similar to your code.

```python
try:
    epQueryResult = []
    for result in api.endpoint.get_all_generator(filter=f'groupId.EQ.greatDevices'):
        if result.response and result.response.SearchResult and result.response.SearchResult.resources:
            epQueryResult.extend(result.response.SearchResult.resources)
except ApiError as e:
    print(e)
```

**Comment by netgab** [comment]
Hi,
sorry, missed that. Thanks for pointing out!
