### ISSUE TITLE
Need API support for Egress Matrix Policy Push and other APIs under Global Operations of API documentation

### ISSUE THREAD

**Issue by mandurai** [CiscoISE/ciscoisesdk#30]
**Is your feature request related to a problem? Please describe.**
API missing for Egress Matrix Policy Push

**Describe the solution you'd like**
API support for `/ers/config/op/trustsec/egresspolicypush`

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/103135285/189090240-cc593f8c-993b-458c-a01f-db110077c366.png)

**Comment by bvargasre** [comment]
@mandurai
Currently ciscoisesdk does not support those endpoints, but there is a way to use it by using `custom caller`, I attach a link that shows the use of the method https://ciscoisesdk.readthedocs.io/en/latest/api/quickstart.html#adding-api-call-definitions.
Anyway, if you have any doubt, please let me know.

**Comment by bvargasre** [comment]
@mandurai 
Issue closed due to inactivity
