### ISSUE TITLE
node_deployment API methods is not returning proper response

### ISSUE THREAD

**Issue by mandurai** [CiscoISE/ciscoisesdk#31]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?

**Describe the bug**
`node_deployment.get_nodes() `returns html login page as rest response instead of node details
whereas other APIs are working properly

```
(Pdb) result = self.api.node_deployment.get_node_details('cts-auto-v4-ise1').response
(Pdb) result [:100]
'<!doctype html>\n<!--**************************************************-->\n<!-- Copyright (c) 2020 Ci'

(Pdb) result = self.api.node_deployment.get_nodes().response
(Pdb) result [:100]
'<!doctype html>\n<!--**************************************************-->\n<!-- Copyright (c) 2020 Ci'


(Pdb) self.api.network_device.get_all().response
{'SearchResult': {'total': 1, 'resources': [{'id': '14199ca0-30da-11ed-9c2f-164d3c298156', 'name': 'temp_device', 'description': '', 'link': {'rel': 'self', 'href': 'https://10.76.119.182/ers/config/networkdevice/14199ca0-30da-11ed-9c2f-164d3c298156', 'type': 'application/json'}}]}}
(Pdb) 

```

**Expected behavior**
get_nodes should return node details

```
{
    "SearchResult": {
        "total": 3,
        "resources": [
            {
                "id": "1dc8a010-2a6e-11ed-a7df-0050568a6359",
                "name": "cts-auto-v4-ise1",
                "link": {
                    "rel": "self",
                    "href": "https://10.76.119.182/ers/config/node/1dc8a010-2a6e-11ed-a7df-0050568a6359",
                    "type": "application/json"
                }
            },
            {
                "id": "fb751a70-2ae0-11ed-a950-164d3c298156",
                "name": "cts-auto-v4-ise2",
                "link": {
                    "rel": "self",
                    "href": "https://10.76.119.182/ers/config/node/fb751a70-2ae0-11ed-a950-164d3c298156",
                    "type": "application/json"
                }
            },
            {
                "id": "2a208180-2e78-11ed-91a9-164d3c298156",
                "name": "cts-auto-v4-ise3",
                "link": {
                    "rel": "self",
                    "href": "https://10.76.119.182/ers/config/node/2a208180-2e78-11ed-91a9-164d3c298156",
                    "type": "application/json"
                }
            }
        ]
    }
}
```

**Screenshots**
Working in Postman:

![image](https://user-images.githubusercontent.com/103135285/189474690-6cb9feb2-d473-48b4-a6c4-dc75bce7cba7.png)

**Environment (please complete the following information):**
* ISE version and patch: ISE 3.1
* Python version: Python 3.8.2
* SDK version: 2.0.4
* OS version: 

**Additional context**

**Comment by bvargasre** [comment]
Hi @mandurai 
This behavior may be due to the fact that you have not configured two parameters on the lab side
Check that these two parameters are activated and save the change

+ ERS (Read/Write)
+ Open API (Read/Write)
                                    

![image](https://user-images.githubusercontent.com/93611706/189394468-5b425285-becb-44ad-b8ba-1750835fea72.png)

##
If the problem persist, let us know

**Comment by mandurai** [comment]
@bvargasre I have enabled ERS, also check my postman screenshot. Other APIs are working fine.

Open API is not enabled as not using it.

```
(Pdb) result = self.api.node_deployment.get_nodes().response
(Pdb) 
(Pdb) self.api.network_device.get_all().response
{'SearchResult': {'total': 1, 'resources': [{'id': '14199ca0-30da-11ed-9c2f-164d3c298156', 'name': 'temp_device', 'description': '', 'link': {'rel': 'self', 'href': 'https://10.76.119.182/ers/config/networkdevice/14199ca0-30da-11ed-9c2f-164d3c298156', 'type': 'application/json'}}]}}
(Pdb) result [:100]
'<!doctype html>\n<!--**************************************************-->\n<!-- Copyright (c) 2020 Ci'
(Pdb) 
```

![image](https://user-images.githubusercontent.com/103135285/189474497-c8cacfbb-97c1-4bcc-8814-9f18dd6fa03e.png)

![image](https://user-images.githubusercontent.com/103135285/189474533-2bb67c55-79b0-4bd1-adad-dbcb6254a59a.png)

**Comment by bvargasre** [comment]
@mandurai 
What happens is that the collection assumes that both are activated.
![image](https://user-images.githubusercontent.com/93611706/189739478-3b7e3dfc-0f0a-48cd-82e4-461e4eb32c20.png)

**Comment by mandurai** [comment]
@bvargasre After enabling both ERS and Open API, api is throwing exception. In both the cases, requests via postman is working fine.
```

(Pdb) self.api.network_device.get_all().response
{'SearchResult': {'total': 1, 'resources': [{'id': '14199ca0-30da-11ed-9c2f-164d3c298156', 'name': 'temp_device', 'description': '', 'link': {'rel': 'self', 'href': 'https://10.76.119.182/ers/config/networkdevice/14199ca0-30da-11ed-9c2f-164d3c298156', 'type': 'application/json'}}]}}

(Pdb) self.api.node_deployment.get_nodes()
*** ciscoisesdk.exceptions.ApiError: [404] - The URI requested is invalid or the resource requested, such as a user, does not exist. Also returned when the requested format is not supported by the requested method.
(Pdb) 
```


![image](https://user-images.githubusercontent.com/103135285/189805393-3226682f-8fdc-4e0a-bdb0-ae70b2be904f.png)

**Comment by bvargasre** [comment]
@mandurai What I see is that you are confusing endpoints.
You are using `self.api.node_deployment.get_nodes()`, but it refers to this endpoint `base_url/api/v1/deployment/node/` and most likely you have no data there, that's why the 404.
And the one you use in postman is `base_url/ers/config/node` which is `self.api.node_details.get_node_details()`.

**Comment by bvargasre** [comment]
Hi, @mandurai 
Gently reminder to comment if there is any problem or doubt. If there are no comments, I will close this topic for inactivity this Friday.

**Comment by mandurai** [comment]
@bvargasre Sorry for the delay, your suggestion worked thanks.
