### ISSUE TITLE
issue with network access network conditions

### ISSUE THREAD

**Issue by paulcana** [CiscoISE/ciscoisesdk#32]
**Prerequisites**
* [ x] Have you tested the operation in the API directly?
* [ x] Do you have the latest SDK version?

**Describe the bug**
Impossible to configure conditions for Network access network conditions
https://github.com/CiscoISE/ciscoisesdk/blob/main/ciscoisesdk/api/v3_1_1/network_access_network_conditions.py

**Expected behavior**
SDK is expecting a parameter named "conditions" with a list of conditions. API is expecting a list of conditions for each condition type
in attributes ipAddrList, deviceList,deviceGroupList
These 3 parameters are not handled by the SDK

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.
![image](https://user-images.githubusercontent.com/69456907/193610432-2b363dbd-2622-4ba2-ad3b-4447e511aab9.png)

**Environment (please complete the following information):**
* ISE version and patch: 3.1 patch 3
* Python version: 3.10
* SDK version: 2.0.4
* OS version: docker

**Additional context**

**Comment by bvargasre** [comment]
Hi @paulcana
The ciscoisesdk v2.0.5 is available. Feel free to test it and close or comment if necessary.

**Comment by bvargasre** [comment]
I am closing this issue, as it was the same problem as ansible-ise #57 which is solved.
