### ISSUE TITLE
ISE CoA API - Wrong Endpoint in SDK

### ISSUE THREAD

**Issue by maconrad** [CiscoISE/ciscoisesdk#34]
**Prerequisites**
* [ ] Have you tested the operation in the API directly? Yes
* [ ] Do you have the latest SDK version? Yes

**Describe the bug**
API Endoint contains character it should not (>)
 e_url = ('/admin/API/mnt/CoA/Disconnect>/... instead of
 e_url = ('/admin/API/mnt/CoA/Disconnect/... 

Therefore you get HTTP 400, Request not processed - Bad input

**Expected behavior**
Correct API endpoint.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/11851898/198237242-50c23b3b-e257-4240-84c3-62f70f156f2e.png">

**Environment (please complete the following information):**
* ISE version and patch: 3.1 
* Python version:  3.9
* SDK version: tested 3.1, 3.1 patch 1
* OS version: OSX

**Additional context**
Would be nice if you could also name the variables correctly.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/11851898/198237487-c5fb794f-32d2-41d7-8d1a-aaa04dc22f58.png">

So e.g. disconnect_type instead of dis_con_nec_tty_pe, psn_name instead of psn_nam_e etc.

Thank you

**Comment by bvargasre** [comment]
Hi @maconrad, The ciscoisesdk v2.0.6 is available. Feel free to test it and close or comment if necessary.

**Comment by wastorga** [comment]
@bvargasre, I think we could remove also the extra {} enclosing the ENDPOINT_IP parameter, or change it in our internal apply_path_params function.

**Comment by bvargasre** [comment]
@wastorga, Fixed it

**Comment by bvargasre** [comment]
Closed due to inactivity
