### ISSUE TITLE
list_installed_hotpatches only returns most recent hotpatch

### ISSUE THREAD

**Issue by mcgowanjt** [CiscoISE/ciscoisesdk#48]
**Describe the bug**
When I call "list_installed_hotpatches", I only get the most recently installed hotpatch.

**Expected behavior**
I would expect it to return all of the installed hotpatches. I have tried on a few of my ISE nodes and it always returns a list with only 1 hotpatch even if I know there are more.

**Screenshots**
![Screenshot 2023-07-03 at 10 23 03 AM](https://github.com/CiscoISE/ciscoisesdk/assets/83037105/7c6bbd9a-f06d-416a-b0a3-6987fcc7dd71)

<img width="525" alt="Screenshot 2023-07-03 at 10 23 14 AM" src="https://github.com/CiscoISE/ciscoisesdk/assets/83037105/644d356b-0628-4b1c-af07-438e16faf1cc">

**Environment (please complete the following information):**
* ISE version and patch: 3.1.0 Patch 7
* Python version: 3.10.5
* SDK version: 2.0.9
* OS version: MacOS 13.4.1 (Ventura)

**Comment by bvargasre** [comment]
Hello @mcgowanjt , try it with postman and attach the result
`<host>/api/v1/hotpatch`

**Comment by bvargasre** [comment]
Hi @mcgowanjt 

I'm going to close this issue due to inactivity
If you have a new problem feel free to create a new issue
Regards
