### ISSUE TITLE
export_system_certicate "message" : "HostName should not be null"

### ISSUE THREAD

**Issue by Skizzzz** [CiscoISE/ciscoisesdk#49]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ciscoisesdk/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
When trying to export the system cert I get this error but looking at the docs there is no requirement for hostname and I'm unable to add a hostname.

search_result = api.certificates.export_system_certificate(export='CERTIFICATE_WITH_PRIVATE_KEY', id='9d6xxxxd-6xx3-4xx1-xxx2-1eaxxxxx732f', password='TestCiscoIseAPI')

==================================================
Traceback (most recent call last):

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/api/v3_1_patch_1/certificates.py", line 1292, in export_system_certificate
    _api_response = self._session.post(endpoint_full_url, params=_params,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/restsession.py", line 640, in post
    return self.download('POST', url, erc, 0, params=params,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/restsession.py", line 422, in download
    with self.request(method, url, erc, 0, **kwargs) as resp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [400] - HostName should not be null
{
  "status" : "Fail",
  "message" : "HostName should not be null"

**Environment (please complete the following information):**
* ISE version and patch: 3.1 Patch 7 
* Python version: 3.10
* SDK version: Latest
* OS version: Mac OS

**Additional context**

**Comment by bvargasre** [comment]
Hi @Skizzzz, This issue seems to be due to the ISE version, in new versions they ask for the hostname,
3.1 patch 1 :
![image](https://github.com/CiscoISE/ciscoisesdk/assets/93611706/612e6141-51e1-4af8-b6fe-272545fbf3c1)


Currently 3.1 Patch 7 version is not supported, but there is a workaround

``` python
payload = {
    'export': 'CERTIFICATE_WITH_PRIVATE_KEY',
    'id': '9d6xxxxd-6xx3-4xx1-xxx2-1eaxxxxx732f',
    'password': 'TestCiscoIseAPI',
    'hostname': 'hostname'
}

search_result = api.certificates.export_system_certificate(payload=payload)
```

**Comment by jltaylor32** [comment]
I tried the work around and still get this error:

api = IdentityServicesEngineAPI(username='admin',
                                password='XXXXXXXXXX',
                                uses_api_gateway=True,
                                base_url='https://aaa01-XXXXXXXX',
                                version='3.1_Patch_1',
                                verify=False,
                                debug=False,
                                uses_csrf_token=False)


payload = {
    'export': 'CERTIFICATE_WITH_PRIVATE_KEY',
    'id': '12bXXXXX-3XXX2-4XXc-b5e2-17XXXXXXXc394',
    'password': 'TestCiscoIseAPI',
    'hostname': 'aaa01-XXX.XXXXXXt.com'
}



search_result = api.certificates.export_system_certificate(payload=payload)

Any ideas?

==================================================
Traceback (most recent call last):
  File "/Users/jtaylor/Desktop/Apogee/Code/Cisoc ISE/new.py", line 27, in <module>
    search_result = api.certificates.export_system_certificate(payload=payload)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/api/v3_1_patch_1/certificates.py", line 1292, in export_system_certificate
    _api_response = self._session.post(endpoint_full_url, params=_params,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/restsession.py", line 640, in post
    return self.download('POST', url, erc, 0, params=params,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/restsession.py", line 422, in download
    with self.request(method, url, erc, 0, **kwargs) as resp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [400] - HostName should not be null
{
  "status" : "Fail",
  "message" : "HostName should not be null"
}

**Comment by bvargasre** [comment]
@Skizzzz my bad, following the new doc, the field is called hostName and not hostname
![image](https://github.com/CiscoISE/ciscoisesdk/assets/93611706/919a5786-6634-413f-ace0-d88633f2e339)

Try it again with
``` python
payload = {
    'export': 'CERTIFICATE_WITH_PRIVATE_KEY',
    'id': '9d6xxxxd-6xx3-4xx1-xxx2-1eaxxxxx732f',
    'password': 'TestCiscoIseAPI',
    'hostName': 'aaa01-XXX.XXXXXXt.com'
}

search_result = api.certificates.export_system_certificate(payload=payload)
```

**Comment by jltaylor32** [comment]
AHHH! This works! I'm going to be exporting hundreds of certs from multiple deployments. Is there good documentation on exporting the certificate file and the key file and saving them? Haven't found exactly what im looking for and what I have tried doesn't seem to export them correctly into the separate files. Or if you have any recommendation that would be great!

**Comment by bvargasre** [comment]
This is the documentation:
https://ciscoisesdk.readthedocs.io/en/latest/api/api.html#ciscoisesdk.api.v3_1_patch_1.certificates.Certificates.export_system_certificate

Example:
``` python
api.file.export_system_certificate(files.response[0].id, dirpath='/PATH/Downloads', save_file=True, filename='20221222225353910_Cisco_KnownGoodValues.tar')
```

**Comment by bvargasre** [comment]
I'm going to close the issue if you have any problems feel free to reopen it or create a new one
Regards
