### ISSUE TITLE
Unable to install isesdk and dnacentersdk in same env

### ISSUE THREAD

**Issue by oianson** [CiscoISE/ciscoisesdk#51]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [ ] Do you have the latest SDK version?
* [ ] Review the [compatibility matrix](https://github.com/CiscoISE/ciscoisesdk/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**

When trying to install the latest ciscoisesdk and dnacentersdk in my environment, I am getting the following error. Can the dependencies for the request-toolbelt be updated/relaxed? 

```
#18 109.9 The conflict is caused by:
#18 109.9     dnacentersdk 2.6.6 depends on requests-toolbelt<2.0.0 and >=1.0.0
#18 109.9     ciscoisesdk 2.0.10 depends on requests-toolbelt<0.11.0 and >=0.10.1
```

**Expected behavior**

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* ISE version and patch:
* Python version: 3.9
* SDK version: 
* OS version: 

**Additional context**

**Comment by bvargasre** [comment]
Hi @oianson new version of ciscoisesdk 2.0.11 has been released, try installing again

**Comment by oianson** [comment]
> Hi @oianson new version of ciscoisesdk 2.0.11 has been released, try installing again

Thanks!
