### ISSUE TITLE
Documentation bug in Repository class methods (name parameter)

### ISSUE THREAD

**Issue by netgab** [CiscoISE/ciscoisesdk#57]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ciscoisesdk/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**

In the API documentation for the `Repository` class (https://ciscoisesdk.readthedocs.io/en/latest/api/api.html#ciscoisesdk.api.v3_1_0.repository.Repository), the repository name parameter does not match the actual implementation.

For example the `get_repository` method expects the parameter `name` according to the documentation.
When using the `name` parameter, the following exception is raised:

```
TypeError: Repository.get_repository() missing 1 required positional argument: 'repository_name'
```

**Expected behavior**

Not fully clear.

Option 1: Change API implementation according to the documentation (`name`) parameter.
However, this will potentially break any existing programs relying on the SDK. So maybe option 2 is 
the better approach.

Option 2: Change the documentation and replace `name` with `repository_name` in the corresponding methods

**Environment (please complete the following information):**
* ISE version and patch: 3.2 Patch 4 (not relevant in this case)
* Python version: 3.11.6
* SDK version: ciscoisesdk==2.0.12

**Comment by bvargasre** [comment]
Hi @netgab

Check the parameter and it is fine, what happens is that in v3.1.0 it was name, but for versions from v3.1 patch 1 to the newest currently supported version of v3.3_patch_1 it was changed to repository_name
Most likely you have checked the v3.1.0 docs and used other versions for the sdk
I'm going to close the issue, in case the problem persists feel free to reopen the issue or create a new one
Regards
