### ISSUE TITLE
ModuleNotFoundError: No module named 'ciscoisesdk.api.v3_2_beta.nbar_app'

### ISSUE THREAD

**Issue by netgab** [CiscoISE/ciscoisesdk#59]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ciscoisesdk/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**

Just created my new ISE testing development container with the new ciscoisesdk 2.1.0 version.
When running my scripts, the following exception is raised:
```
ModuleNotFoundError: No module named 'ciscoisesdk.api.v3_2_beta.nbar_app'
```
This even happens from the Python CLI:

```
ise-testing@1654ae340d2b:~$ python3
Python 3.11.6 (main, Nov  1 2023, 13:45:43) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from ciscoisesdk import IdentityServicesEngineAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.11/site-packages/ciscoisesdk/__init__.py", line 31, in <module>
    from .api import IdentityServicesEngineAPI
  File "/opt/venv/lib/python3.11/site-packages/ciscoisesdk/api/__init__.py", line 1487, in <module>
    from .v3_2_beta.nbar_app import (
ModuleNotFoundError: No module named 'ciscoisesdk.api.v3_2_beta.nbar_app'
>>> 
```

**Expected behavior**

Working import

**Environment (please complete the following information):**
* ISE version and patch: 3.2 Patch 4 (but irrelevant here)
* Python version: 3.11.6
* SDK version: ciscoisesdk==2.1.0
* OS version: Debian 12.2 (container image `python:3.11-slim-bookworm`)

**Comment by bvargasre** [comment]
Hi @netgab  ciscoisesdk version 2.1.1 is now available, try this new version and tell us if it works for you or if you have any other problems

**Comment by netgab** [comment]
Works like a charm with the new version ... Thanks for taking care!
