### ISSUE TITLE
ModuleNotFoundError: No module named 'imp' runtime within PyCharm (python 3.12)

### ISSUE THREAD

**Issue by andyo-ua** [CiscoISE/ciscoisesdk#62]
**Prerequisites**
* [No] Have you tested the operation in the API directly?
* [Yes ] Do you have the latest SDK version?
* [Yes ] Review the [compatibility matrix](https://github.com/CiscoISE/ciscoisesdk/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
After adding package to venv in PyCharm (python 3.12) & running trough code below. Traceback shoot with bottom line of "ModuleNotFoundError: No module named 'imp'"

from ciscoisesdk import IdentityServicesEngineAPI
from ciscoisesdk.exceptions import ApiError
api = IdentityServicesEngineAPI(username='admin',
                                password='Cisco123',
                                uses_api_gateway=True,
                                base_url='https://10.200.200.50',
                                version='3.2_beta',
                                verify=False,
                                debug=False,
                                uses_csrf_token=False)
**Expected behavior**
silent code execution

**Screenshots**
curl -X 'GET' \
  'https://10.200.200.50:443/api/v1/patch' \
  -H 'accept: application/json'

{
  "iseVersion": "3.2.0.542",
  "patchVersion": [
    {
      "patchNumber": 2,
      "installDate": "Thu Jul 06 18:46:47 2023"
    }
  ]
}

**Environment (please complete the following information):**
* ISE version and patch: 3.2.0.542 patch 2
* Python version: 3.12
* SDK version: 2.1.2
* OS version: Win10 ent 10.0.19044

**Additional context**

**Comment by markatdxb** [comment]
I'm getting similar issue with Python 3.12 when using together with Ansible. 

Getting error  
```
"msg": "Cisco ISE Python SDK is not installed. Execute 'pip install ciscoisesdk'",
"exception": "NoneType: None\n",
```

No issues when running the same code in venv with Python 3.9x

**Comment by andystevenscodes** [comment]
Same thing when loading this op to Digital Oceans


[wur-project-itws] [2024-04-24 19:26:57]     from future import standard_library
[wur-project-itws] [2024-04-24 19:26:57]   File "/workspace/.heroku/python/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
[wur-project-itws] [2024-04-24 19:26:57]     import imp
[wur-project-itws] [2024-04-24 19:26:57] ModuleNotFoundError: No module named 'imp'
[wur-project-itws] [2024-04-24 19:26:57] [2024-04-24 19:26:57 +0000] [14] [INFO] Worker exiting (pid: 14)
[wur-project-itws] [2024-04-24 19:26:57] [2024-04-24 19:26:57 +0000] [1] [ERROR] Worker (pid:14) exited with code 3
[wur-project-itws] [2024-04-24 19:26:57] [2024-04-24 19:26:57 +0000] [1] [ERROR] Shutting down: Master
[wur-project-itws] [2024-04-24 19:26:57] [2024-04-24 19:26:57 +0000] [1] [ERROR] Reason: Worker failed t

I already try to to replace imp with importlib in the future module directly which is rely on imp). 
But still I get this message. Later I realised in the future > standard_librarry __Init__.py the docker in oceans will never see this change, locally I have no issue's I use future version: 0.18.3. 
When I use version 1.0.0 where there is a fix in place to look at he python version is not compatible with Ciscoisesdk... "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ciscoisesdk 2.1.2 requires future<0.19.0,>=0.18.3, but you have future 1.0.0 which is incompatible"

**Comment by bvargasre** [comment]
Hi @andyo-ua 

In the new version of ciscoisesdk v2.2.2 the problem had to be solved
I'm going to close the issue, if you have a problem feel free to reopen the issue or create a new one
Regards
