### ISSUE TITLE
Time to update dependences on request

### ISSUE THREAD

**Issue by elear** [CiscoISE/ciscoisesdk#64]
**Prerequisites**
* [yes] Have you tested the operation in the API directly?
* [yes] Do you have the latest SDK version?
* [did] Review the [compatibility matrix](https://github.com/CiscoISE/ciscoisesdk/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**

ciscoisesdk 2.1.2 requires requests<=2.28,>=2.27.1, but you have requests 2.31.0 which is incompatible.

So I downgrade.  But...

AND

responses 0.25.0 requires requests<3.0,>=2.30.0, but you have requests 2.28.0 which is incompatible.

**Expected behavior**
the SDK should install with pip.

**Screenshots**
See above.

**Environment (please complete the following information):**
* ISE version and patch: doesn't matter
* Python version: 3.10.13
* SDK version: 

Name: ciscoisesdk
Version: 2.1.2
{...}

* OS version: MacOS 14.3.1

**Additional context**

The sdk needs to update to a later version of requests.

**Comment by oboehmer** [comment]
I support this request (no pun intended ;-) ) to relax the requirement on `request` library..
