### ISSUE TITLE
create_network_device_group not working correctly

### ISSUE THREAD

**Issue by duk2nuk** [CiscoISE/ciscoisesdk#69]
**Prerequisites**
* [ x] Have you tested the operation in the API directly?
* [x ] Do you have the latest SDK version?
* [x ] Review the [compatibility matrix](https://github.com/CiscoISE/ciscoisesdk/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
Function "create_network_device_group" return en error: 
[400] - Validation Error - Mandatory fields missing: [ndgtype]
even if ndgtype parametr is provided:

response = api.network_device_group.create_network_device_group(ndgtype="Device Type", name=f"'Location#All Locations#{loc}", description=dsc)
What I am doing wrong?

**Expected behavior**

**Screenshots**
![Screenshot 2024-05-16 180654](https://github.com/CiscoISE/ciscoisesdk/assets/85095762/0657a98f-3d86-45f2-94b7-64f87806e730)

**Environment (please complete the following information):**
* ISE version and patch: 3.2.0.542
* Python version: 3.10
* SDK version:  2.2.1
* OS version: Ubuntu 22.04.4 LTS

**Additional context**

**Comment by bvargasre** [comment]
Hi @duk2nuk

As such there is no problem, what happened is that CiscoISE had a bug with create network device group, you can see it here
https://bst.cisco.com/bugsearch/bug/CSCwd24304
In short ndgtype should not have existed

I will close the issue if you have any problem feel free to reopen
Regards
